@startuml Level 2 Sequence Diagram for US 5.1.3
actor Patient
participant AuthController as Controller
participant CognitoAuthService as AuthService
participant IPatientProfileRepository as Repository
participant IAmazonCognitoIdentityProvider as IAM

activate Patient
Patient -> Controller: initiate registration
activate Controller

Controller -> AuthService: sign up patient
activate AuthService

AuthService -> Repository: check if patient exists
activate Repository
Repository --> AuthService: patient exists
deactivate Repository

AuthService -> IAM: register patient
activate IAM
IAM --> AuthService: send verification email
deactivate IAM

AuthService --> Controller: registration successful
deactivate AuthService

Controller --> Patient: notify verification email sent
deactivate Controller

Patient -> IAM: confirm email
activate IAM
IAM --> AuthService: email confirmed
deactivate IAM

activate AuthService


AuthService --> Controller: email confirmed
deactivate AuthService

activate Controller

Controller --> Patient: registration successful
deactivate Controller
deactivate Patient

@enduml