@startuml
title Use Case Diagram - Global

left to right direction

actor Admin #F0E68C
actor User #F0E68C
actor Patient #F0E68C
actor Doctor #F0E68C
actor HealthCareStaff #F0E68C
actor SystemAdministrator #F0E68C
actor Entity #F0E68C
actor System #F0E68C

skinparam usecase {
    BackgroundColor LightBlue
    ArrowColor Black
    BorderColor Black
    FontColor Black
    FontSize 14
}

skinparam title {
    FontSize 30
}

rectangle BackofficeModule #87CEFA {
    'SPRINT A
    
    usecase "Register a new User" as UC1.1 #F0E68C
    Admin --> UC1.1
   
    usecase "Send a setup link via email to activate an account" as UC1.2 #F0E68C
    Admin --> UC1.2
   
    usecase "Reset Password" as UC2 #F0E68C
    User --> UC2
   
  usecase "Create a user profile"  as UC3.1 #F0E68C
   Patient --> UC3.1
   
   usecase "Book appointments online" as UC3.2 #F0E68C
   Patient --> UC3.2 
     
    usecase "Update user Profile" as UC4 #F0E68C
    Patient --> UC4
   
    usecase "Delete Account and Associated Data " as UC5 #F0E68C
    Patient --> UC5
   
    usecase "Acess Features" as UC6 #F0E68C
   
    usecase "Login" as UC7 #F0E68C
    Patient --> UC7
   
    usecase "Create a new patient profile" as UC8 #F0E68C
    Admin --> UC8
   
    usecase "Update a Patient Profile" as UC9 #F0E68C
    Admin --> UC9
   
    usecase "Delete a patient profile " as UC10 #F0E68C
    Admin --> UC10
   
    usecase "List/search patient profiles" as UC11 #F0E68C
    Admin ---> UC11
   
    usecase "Create a new staff profile" as UC12 #F0E68C
    Admin --> UC12

    usecase "Edit a staff´s profile" as UC13 #F0E68C
    Admin --> UC13

    usecase "Deactivate a staff profile" as UC14 #F0E68C
    Admin --> UC14

    usecase "List/search staff profiles" as UC15 #F0E68C
    Admin --> UC15

    usecase "Create an Operation Requisition" as UC16 #F0E68C
    Doctor --> UC16
   
    usecase "Update an Operation Requisition" as UC17 #F0E68C
    Doctor --> UC17
   
    usecase "Remove an Operation Requisition" as UC18 #F0E68C
    Doctor --> UC18
   
    usecase "List/Search Operation Requisitions" as UC19 #F0E68C
    Doctor --> UC19
   
    usecase "Create an Operation Type" as UC20 #F0E68C
    Admin --> UC20
   
    usecase "Update an Operation Type" as UC21 #F0E68C
    Admin --> UC21
   
    usecase "Deactivate an Operation Type" as UC22 #F0E68C
    Admin --> UC22
   
    usecase "List/Search Operation Types" as UC23 #F0E68C  
    Admin --> UC23   


    'SPRINT B
    usecase "Have an integrated UI for all modules" as UC24 #F0E68C
    User --> UC24

    usecase "Application menu to adjust according to my role" as UC25 #F0E68C
    User --> UC25

    usecase "Synchronization 3D model with Planing module" as UC26 #F0E68C
    Admin --> UC26

    usecase "Synchronization Planing Module with the Backoffice Module " as UC27 #F0E68C
    Admin --> UC27

    usecase "Synchronization e information about staff’s availability and operation schedule with the Planing Module" as UC28 #F0E68C
    Admin --> UC28

    usecase "Obtain the better scheduling of a set of operations (surgeries) in a certain operation room in a specific day" as UC29 #F0E68C
    Admin --> UC29

    usecase "Know the dimension in terms of number of surgeries is possible to ask for the better solutioneration room in a specific day" as UC30 #F0E68C
    Admin --> UC30

    usecase "Obtain a good schedule, not necessarily the better, in useful time to be adopted" as UC31 #F0E68C
    Admin --> UC31

    usecase "I want the deployment of one of the RFP modules in a DEI VM to be systematic, validating it on a scheduled basis with the test plan." as UC32 #F0E68C
    SystemAdministrator --> UC32

    usecase "r, I only want clients on the DEI's internal network (wired or via VPN) to be able to access the solution" as UC33 #F0E68C
    SystemAdministrator --> UC33

    usecase ", I want the clients listed in the requirement 6.3.2 to be able to be defined by simply changing a text file." as UC34 #F0E68C
    SystemAdministrator --> UC34

    usecase "I want to identify and quantify the risks involved in the recommended solution" as UC35 #F0E68C
    Admin --> UC35

    usecase "I want to define the MBCO (Minimum Business Continuity Objective) to propose to stakeholders" as UC36 #F0E68C
    SystemAdministrator --> UC36

    usecase "r, I want a backup strategy to be proposed, justified and implemented that minimizes RPO (Recovery Point Objective) and WRT (Work Recovery Time)." as UC37 #F0E68C
    SystemAdministrator --> UC37

    usecase "r I want to define a public folder for all users registered on the system, where they can read whatever is placed there" as UC38 #F0E68C
    SystemAdministrator --> UC38

    usecase "I want to get users with more than 3 incorrect accesses attempts" as UC39 #F0E68C
    SystemAdministrator --> UC39

    usecase "See a 3D representation of the hospital/clinic floor" as UC40 #F0E68C
    HealthCareStaff --> UC40

    usecase "See appropriate textures (that is, suitable for use in representing a hospital or clinic) mapped onto the floor, walls, and so on." as UC41 #F0E68C
    HealthCareStaff --> UC41

    usecase "See the hospital/clinic floor illuminated with ambient and directional light." as UC42 #F0E68C
    HealthCareStaff --> UC42

    usecase "I want to control the camera with the mouse" as UC43 #F0E68C
    HealthCareStaff --> UC43

    usecase "Know how the project may affect patients' personal data and if the processing is done according to the law." as UC44 #F0E68C
    Entity --> UC44

    usecase "Notify both users and the responsible authority in case of a data breach, so that I comply with GDPR’s breach notification requirements." as UC45 #F0E68C
    System --> UC45


}

@enduml